const standardsSchema = [
  `CREATE TABLE IF NOT EXISTS standards (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    code VARCHAR(120) NOT NULL,
    category VARCHAR(80) NOT NULL,
    standard_level VARCHAR(40) NOT NULL DEFAULT 'industry',
    publisher VARCHAR(255) NOT NULL,
    publish_date DATE,
    effective_date DATE NOT NULL,
    abolished_date DATE,
    status ENUM('draft','pending_review','published','deprecated','archived') NOT NULL DEFAULT 'draft',
    applicable_scope TEXT NOT NULL,
    version_label VARCHAR(80) NOT NULL,
    replacement_standard_id BIGINT,
    current_version_id BIGINT,
    created_by INT,
    created_by_name VARCHAR(100),
    reviewed_by INT,
    reviewed_by_name VARCHAR(100),
    reviewed_at DATETIME,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    UNIQUE KEY uk_standard_code_version (code, version_label),
    INDEX idx_standard_category (category),
    INDEX idx_standard_status (status),
    INDEX idx_standard_effective_date (effective_date),
    FOREIGN KEY (replacement_standard_id) REFERENCES standards(id) ON DELETE SET NULL,
    FOREIGN KEY (created_by) REFERENCES users(id) ON DELETE SET NULL,
    FOREIGN KEY (reviewed_by) REFERENCES users(id) ON DELETE SET NULL
  ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci`,

  `CREATE TABLE IF NOT EXISTS standard_versions (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    standard_id BIGINT NOT NULL,
    version_no INT NOT NULL DEFAULT 1,
    version_label VARCHAR(80) NOT NULL,
    file_asset_id BIGINT NOT NULL,
    page_count INT NOT NULL DEFAULT 0,
    full_text LONGTEXT,
    page_text LONGTEXT,
    change_note TEXT,
    created_by INT,
    created_by_name VARCHAR(100),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UNIQUE KEY uk_standard_version_no (standard_id, version_no),
    INDEX idx_standard_version_asset (file_asset_id),
    FOREIGN KEY (standard_id) REFERENCES standards(id) ON DELETE CASCADE,
    FOREIGN KEY (file_asset_id) REFERENCES file_assets(id) ON DELETE RESTRICT,
    FOREIGN KEY (created_by) REFERENCES users(id) ON DELETE SET NULL
  ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci`,

  `CREATE TABLE IF NOT EXISTS standard_clauses (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    standard_id BIGINT NOT NULL,
    version_id BIGINT NOT NULL,
    clause_no VARCHAR(80),
    title VARCHAR(255),
    page_no INT NOT NULL,
    content TEXT NOT NULL,
    keywords VARCHAR(500),
    created_by INT,
    created_by_name VARCHAR(100),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    INDEX idx_clause_standard (standard_id, version_id),
    INDEX idx_clause_page (version_id, page_no),
    FOREIGN KEY (standard_id) REFERENCES standards(id) ON DELETE CASCADE,
    FOREIGN KEY (version_id) REFERENCES standard_versions(id) ON DELETE CASCADE,
    FOREIGN KEY (created_by) REFERENCES users(id) ON DELETE SET NULL
  ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci`,

  `CREATE TABLE IF NOT EXISTS standard_annotations (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    standard_id BIGINT NOT NULL,
    version_id BIGINT NOT NULL,
    page_no INT NOT NULL,
    selected_text TEXT,
    note TEXT NOT NULL,
    visibility ENUM('private','project') NOT NULL DEFAULT 'private',
    author_id INT,
    author_name VARCHAR(100),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    INDEX idx_annotation_standard (standard_id, version_id, page_no),
    INDEX idx_annotation_author (author_id, visibility),
    FOREIGN KEY (standard_id) REFERENCES standards(id) ON DELETE CASCADE,
    FOREIGN KEY (version_id) REFERENCES standard_versions(id) ON DELETE CASCADE,
    FOREIGN KEY (author_id) REFERENCES users(id) ON DELETE SET NULL
  ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci`,

  `CREATE TABLE IF NOT EXISTS standard_checklist_templates (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    category VARCHAR(80) NOT NULL,
    applicable_stage VARCHAR(80),
    description TEXT,
    status ENUM('draft','published','archived') NOT NULL DEFAULT 'draft',
    created_by INT,
    created_by_name VARCHAR(100),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    INDEX idx_checklist_category (category),
    INDEX idx_checklist_status (status),
    FOREIGN KEY (created_by) REFERENCES users(id) ON DELETE SET NULL
  ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci`,

  `CREATE TABLE IF NOT EXISTS standard_checklist_items (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    template_id BIGINT NOT NULL,
    standard_id BIGINT,
    version_id BIGINT,
    clause_id BIGINT,
    item_text TEXT NOT NULL,
    basis_text TEXT,
    page_no INT,
    sort_order INT NOT NULL DEFAULT 0,
    required TINYINT(1) NOT NULL DEFAULT 1,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    INDEX idx_checklist_item_template (template_id, sort_order),
    FOREIGN KEY (template_id) REFERENCES standard_checklist_templates(id) ON DELETE CASCADE,
    FOREIGN KEY (standard_id) REFERENCES standards(id) ON DELETE SET NULL,
    FOREIGN KEY (version_id) REFERENCES standard_versions(id) ON DELETE SET NULL,
    FOREIGN KEY (clause_id) REFERENCES standard_clauses(id) ON DELETE SET NULL
  ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci`,

  `CREATE TABLE IF NOT EXISTS compliance_tasks (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    task_no VARCHAR(80) NOT NULL UNIQUE,
    title VARCHAR(255) NOT NULL,
    checklist_template_id BIGINT,
    project_id INT,
    section VARCHAR(100),
    slope_id INT,
    monitor_type VARCHAR(80) NOT NULL,
    implementation_stage VARCHAR(80),
    status ENUM('draft','pending_review','pending_rectification','pending_recheck','closed','archived') NOT NULL DEFAULT 'draft',
    inspector_id INT,
    inspector_name VARCHAR(100),
    reviewer_id INT,
    reviewer_name VARCHAR(100),
    review_comment TEXT,
    submitted_at DATETIME,
    closed_at DATETIME,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    INDEX idx_compliance_status (status),
    INDEX idx_compliance_scope (section, slope_id, monitor_type),
    FOREIGN KEY (checklist_template_id) REFERENCES standard_checklist_templates(id) ON DELETE SET NULL,
    FOREIGN KEY (project_id) REFERENCES projects(id) ON DELETE SET NULL,
    FOREIGN KEY (slope_id) REFERENCES slopes(id) ON DELETE SET NULL,
    FOREIGN KEY (inspector_id) REFERENCES users(id) ON DELETE SET NULL,
    FOREIGN KEY (reviewer_id) REFERENCES users(id) ON DELETE SET NULL
  ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci`,

  `CREATE TABLE IF NOT EXISTS compliance_task_items (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    task_id BIGINT NOT NULL,
    checklist_item_id BIGINT,
    standard_id BIGINT,
    version_id BIGINT,
    clause_id BIGINT,
    item_text TEXT NOT NULL,
    basis_text TEXT,
    page_no INT,
    result ENUM('pending','compliant','basically_compliant','non_compliant','not_applicable','to_confirm') NOT NULL DEFAULT 'pending',
    finding TEXT,
    evidence JSON,
    sort_order INT NOT NULL DEFAULT 0,
    updated_by INT,
    updated_by_name VARCHAR(100),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    INDEX idx_task_item_task (task_id, sort_order),
    INDEX idx_task_item_result (result),
    FOREIGN KEY (task_id) REFERENCES compliance_tasks(id) ON DELETE CASCADE,
    FOREIGN KEY (checklist_item_id) REFERENCES standard_checklist_items(id) ON DELETE SET NULL,
    FOREIGN KEY (standard_id) REFERENCES standards(id) ON DELETE SET NULL,
    FOREIGN KEY (version_id) REFERENCES standard_versions(id) ON DELETE SET NULL,
    FOREIGN KEY (clause_id) REFERENCES standard_clauses(id) ON DELETE SET NULL,
    FOREIGN KEY (updated_by) REFERENCES users(id) ON DELETE SET NULL
  ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci`,

  `CREATE TABLE IF NOT EXISTS compliance_rectifications (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    task_id BIGINT NOT NULL,
    task_item_id BIGINT NOT NULL,
    responsible_person VARCHAR(100) NOT NULL,
    due_date DATE NOT NULL,
    status ENUM('pending','in_progress','pending_recheck','closed','overdue') NOT NULL DEFAULT 'pending',
    action_plan TEXT,
    rectification_result TEXT,
    evidence JSON,
    reviewer_id INT,
    reviewer_name VARCHAR(100),
    review_comment TEXT,
    completed_at DATETIME,
    reviewed_at DATETIME,
    created_by INT,
    created_by_name VARCHAR(100),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    UNIQUE KEY uk_rectification_task_item (task_item_id),
    INDEX idx_rectification_status_due (status, due_date),
    FOREIGN KEY (task_id) REFERENCES compliance_tasks(id) ON DELETE CASCADE,
    FOREIGN KEY (task_item_id) REFERENCES compliance_task_items(id) ON DELETE CASCADE,
    FOREIGN KEY (reviewer_id) REFERENCES users(id) ON DELETE SET NULL,
    FOREIGN KEY (created_by) REFERENCES users(id) ON DELETE SET NULL
  ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci`,

  `CREATE TABLE IF NOT EXISTS standard_user_permissions (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    user_id INT NOT NULL,
    permission_code VARCHAR(80) NOT NULL,
    granted_by INT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UNIQUE KEY uk_standard_user_permission (user_id, permission_code),
    FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
    FOREIGN KEY (granted_by) REFERENCES users(id) ON DELETE SET NULL
  ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci`,
]

module.exports = standardsSchema
